CarModificationCenter/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using CarModificationCenter.Models;

namespace CarModificationCenter.Controllers
{
    [AllowAnonymous]
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ContactUs(contact cntct)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage msz = new MailMessage();
                    msz.From = new MailAddress(cntct.Email);//Email which you are getting 
                    //from contact us page 
                    msz.To.Add("gayangunesinghe@gmail.com");//Where mail will be sent 
                    msz.Subject = cntct.Subject;
                    msz.Body = cntct.Message;
                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = "smtp.gmail.com";

                    smtp.Port = 587;

                    smtp.Credentials = new System.Net.NetworkCredential
                        ("gayangunesinghe@gmail.com", "Anuja1995");

                    smtp.EnableSsl = true;

                    smtp.Send(msz);

                    ModelState.Clear();

                    TempData["msg-type"] = "alert-success";
                    TempData["msg-head"] = "Success!!";
                    TempData["msg-des"] = "Thank you for contacting us!!";
                }
                catch (Exception ex)
                {
                    ModelState.Clear();
                    ViewBag.Message = $" Sorry we are facing Problem here {ex.Message}";
                }
            }

            TempData["msg-type"] = "alert-warning";
            TempData["msg-head"] = "Empty Fields!!";
            TempData["msg-des"] = "Please fill in the empty fields and try again!!";

            return View();
        }
    }
}

CarModificationCenter/Controllers/ProjectController.cs
using System.Linq;
using System.Web.Mvc;
using CarModificationCenter.Models;

namespace CarModificationCenter.Controllers
{
    [AllowAnonymous]
    public class ProjectController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Projects
        public ActionResult CompletedProjects()
        {
            return View();
        }

        // GET: ProjectProgress
        public ActionResult ProjectProgress()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProjectProgress(project model)
        {
                var getProjectName = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.ProjectName);
                var materializeProjectName = getProjectName.ToList();
                var ProjectName = materializeProjectName[0];

                var getType = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.Type);
                var materializeType = getType.ToList();
                var Type = materializeType[0];

                var getDesign = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.Design);
                var materializeDesign = getDesign.ToList();
                var Design = materializeDesign[0];

                var getAcceptedDate = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.AcceptedDate);
                var materializeAcceptedDate = getAcceptedDate.ToList();
                var AcceptedDate = materializeAcceptedDate[0];

                var getDeadline = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.Deadline);
                var materializeDeadline = getDeadline.ToList();
                var Deadline = materializeDeadline[0];

                var getStatus = db.Project.Where(u => u.ProjectID == model.ProjectID).Select(u => u.Status);
                var materializeStatus = getStatus.ToList();
                var Status = materializeStatus[0];

                //var getProjectId = db.Project.Where(u => u.CustomerID == model.CustomerID).Select(u => u.ProjectID);
                //var materializeProjectId = getProjectId.ToList();
                //var ProjectId = materializeProjectId[0];

                model.Type = Type;
                model.Design = Design;
                model.AcceptedDate = AcceptedDate;
                model.Deadline = Deadline;
                model.Status = Status;
                model.ProjectName = ProjectName;

                return View(model);
        }
    }
}

CarModificationCenter/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using CarModificationCenter.Models;

namespace CarModificationCenter.Controllers
{
    [AllowAnonymous]    
    public class ShopController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Shop
        public ActionResult ShopNow(int page = 1, int pageSize = 20)
        {
            try
            {
                List<website_vehicles> listVehicles = db.Vehicles.ToList();
                PagedList<website_vehicles> model = new PagedList<website_vehicles>(listVehicles, page, pageSize);
                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // get the vehicle picture from database
        public FileContentResult LoadPicture(int itemId)
        {
            try
            {
                var getPath = db.Vehicles.Where(u => u.Id == itemId).Select(u => u.Picture01);
                var materializePath = getPath.ToList();
                byte[] path = materializePath[0];

                if (path != null)
                {
                    return new FileContentResult(path, "image/png");
                }

                else
                {
                    return null;
                }
            }
            catch (Exception)
            {
                return null;
            }
        }

        //// search shop items
        //public ActionResult ShopSearch(string query, string category, int page = 1, int pageSize = 10)
        //{
        //    List<website_vehicles> listVehicles = db.Vehicles.ToList();
        //    List<website_vehicles> newVehicles = db.Vehicles.ToList();
        //    foreach (var item in listVehicles)
        //    {
        //        if (category == "Manufacturer" && item.Manufacturer != query)
        //        {
        //            newVehicles.Remove(item);
        //        }
        //    }

        //    PagedList<website_vehicles> model = new PagedList<website_vehicles>(newVehicles, page, pageSize);
        //    return View(model);
        //}
    }
}

CarModificationCenter/Views/Shared/_HeaderMain.cshtml
<!--main header with search bar/site logo and shopping cart-->
<div class="header-main">
    <div class="container">
        <div class="col-lg-3">
            <!--site logo-->
            <a href="@Url.Action("Index", "Home")">
                <div class="logo"></div>
            </a>
        </div>
        <div class="col-lg-7">
            <!--search bar-->
            <div class="search">
                @using (Html.BeginForm("ShopNow", "Shop", FormMethod.Post, new { @class = "navbar-form", role = "search" }))
                {
                <div class="form-group">
                    <input class="form-control searchbar" placeholder="Search for products..." type="text">
                    <select class="form-control" id="select">
                        <option selected="selected" disabled>-All Categories-</option>
                        <option>Sport Cars</option>
                        <option>Motor Bikes</option>
                    </select>
                </div>
                    <button type="submit" class="btn btn-primary"><span class="fa fa-search"></span></button>
                        }
            </div>
        </div>
        <div class="col-lg-2">
            <!--shopping cart-->
            <div class="cart">
                <div class="d-flex flex-row align-items-center justify-content-end">
                    <form action="#" method="post">
                        <input name="cmd" value="_cart" type="hidden">
                        <input name="display" value="1" type="hidden">
                        <button class="btn btn-primary" type="submit" name="submit" value="">
                            <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                            Cart
                            <span class="badge" id="cartValue">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--secondary header bar-->
<div class="navbar navbar-default cat-secondary">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#secondary">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="container">
        <div class="navbar-collapse collapse" id="secondary">
            <ul class="nav navbar-nav navbar-left">
                <li class="category">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="fa fa-bars"></span>
                        C A T E G O R I E S
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Modified Cars</a></li>
                        <li><a href="#">Modified Bikes</a></li>
                        <li><a href="#">Car Electronics</a></li>
                        <li><a href="#">Accessories</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li>
                    <a href="@Url.Action("ShopNow", "Shop")">Shop</a>
                </li>
                <li>
                    <a href="@Url.Action("ShopNow", "Shop")">Projects</a>
                </li>
                <li>
                    <a href="@Url.Action("ContactUs","Contact")">Contact</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
            </ul>
        </div>
    </div>
</div>

CarModificationCenter/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vehicles Modification Center</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="main">
                <ul class="nav navbar-nav navbar-left">
                    <!--display phone number and email address-->
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <div class="logo"></div>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <strong style="color: #219ff3">CAR MODIFICATION</strong><strong> CENTRE</strong>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("ShopNow","Shop")">
                            Shop
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("CompletedProjects","Project")">
                            Projects
                        </a>
                    </li>
                    <li>
                        @if (@User.Identity.IsAuthenticated)
                        {
                            <a href="@Url.Action("ProjectProgress","Project")">
                                Project Progress
                            </a>
                        }
                    </li>
                    <li>
                        <a href="@Url.Action("ContactUs","Contact")">
                            Contact
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (@User.Identity.IsAuthenticated)
                        {
                            <img src="@Url.Action("DisplayPicture", "Home")" class="img-thumbnail" />
                        }
                    </li>
                    <li>
                        @if (@User.Identity.IsAuthenticated)
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                @User.Identity.Name<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="@Url.Action("ManageAccount", "UserAccount")">
                                        <span class="fa fa-user-circle" aria-hidden="true"></span>
                                        View profile
                                    </a>
                                </li>
                                @if (User.Identity.Name == "System Adminstrator")
                                {
                                    <li>
                                        <a href="#">
                                            <span class="fa fa-gear" aria-hidden="true"></span>
                                            Settings
                                        </a>
                                    </li>
                                }
                                <li class="divider"></li>
                                <li>
                                    <a href="@Url.Action("Logout", "Auth")">
                                        <span class="fa fa-sign-out" aria-hidden="true"></span>
                                        Logout
                                    </a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <a href="@Url.Action("Registration", "Auth")">
                                <span class="fa fa-pencil-square-o" aria-hidden="true"></span>
                                Register
                            </a>
                        }
                    </li>
                    <li>
                        @if (!@User.Identity.IsAuthenticated)
                        {
                            <a href="@Url.Action("Login", "Auth")">
                                <span class="fa fa-unlock-alt" aria-hidden="true"></span>
                                Login
                            </a>
                        }
                    </li>
                    <!--cart icons-->
                    <li>
                        <form action="#" method="post">
                            <input name="cmd" value="_cart" type="hidden">
                            <input name="display" value="1" type="hidden">
                            <button class="btn btn-default" type="submit" name="submit" value="" style="height: 50px">
                                <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                                Cart
                                <span class="badge" id="cartValue">0</span>
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    @RenderBody() <!--render page details-->
    <!--copyright details-->
    <footer class="modal-footer">
        <div class="copy-right">
            <div class="container">
                <p>
                    © @DateTime.Now.Year Vehicle Modification Center. All rights reserved | Design by
                    <a href="#"> Group SD01.</a>
                </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/Scripts/js")
    <script>
        paypalm.minicartk.render(); //use only unique class names other than paypalm.minicartk.Also Replace same class name in css and minicart.min.js

        paypalm.minicartk.cart.on('checkout', function (evt) {
            var items = this.items(),
                len = items.length,
                total = 0,
                i;

            // Count the number of each item in the cart
            for (i = 0; i < len; i++) {
                total += items[i].get('quantity');
            }

            //if (total < 3) {
            //    alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
            //    evt.preventDefault();
            //}
            paypalm.minicartk.cart.items().forEach(
                alert(console)
            );

            document.getElementById("cartValue").innerHTML = total;
        });
    </script>
</body>
</html>

CarModificationCenter/Views/Shared/_PopupMessageBox.cshtml
<div class="modal fade in" id="popupMessage" tabindex="-1" role="dialog" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-title"></h4>
            </div>
            <div class="modal-body" id="modal-body">
            </div>
        </div>
    </div>
</div>

CarModificationCenter/Views/Shared/_ServiceMessages.cshtml
<!--code for the unfer information service message boxes-->

@if (@TempData["msg-des"] != null){    //Display only if needed
<div class="alert alert-dismissible @TempData["msg-type"]">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    @if (@TempData["msg-head"] != null)
    {
        <h4>@TempData["msg-head"]</h4>//display header when available
    }
    @if (@TempData["msg-sub-head"] != null)
    {
        <strong>@TempData["msg-sub-head"]</strong>  //display sub header when available
    }
    <p>@TempData["msg-des"]</p>
</div>
}